### ISSUE TITLE
error: RNTDeepAR is not abstract and does not override abstract method

### ISSUE THREAD

**Issue by agamsps** [DeepARSDK/example-reactnative#6]
```
error: RNTDeepAR is not abstract and does not override abstract method error(ARErrorType,String) in AREventListener
public class RNTDeepAR extends FrameLayout implements AREventListener, SurfaceHolder.Callback, LifecycleObserver {
       ^
```

```
error: reference to switchEffect is ambiguous
            deepAr.switchEffect(slot, null, 0);
                  ^
  both method switchEffect(String,InputStream,int) in DeepAR and method switchEffect(String,String,int) in DeepAR match
```

```
error: method does not override or implement a method from a supertype
    @Override
    ^
```

I am not sure if this is an issue, i might be wrong somewhere but i have followed all the steps,but getting these three errors while running the project

**Comment by cjvnjde** [comment]
I had the same problem.
Here are my changes to make it works

In the **RNTDeepAR.java** file

```java
...
import android.media.Image;
import ai.deepar.ar.ARErrorType;
...

public class RNTDeepAR ... {
...
// temporary change
//deepAr.switchEffect(slot, null, 0);
...
public void error(ARErrorType var1, String var2) {}
...
@Override
public void frameAvailable(Image var1) {}
...
}
```

**Comment by abdullahsaeed98** [comment]
> I had the same problem.
> Here are my changes to make it work
> 
> In the **RNTDeepAR.java** file
> 
> ```java
> ...
> import android.media.Image;
> import ai.deepar.ar.ARErrorType;
> ...
> 
> public class RNTDeepAR ... {
> ...
> // temporary change
> //deepAr.switchEffect(slot, null, 0);
> ...
> @Override
> public void error(ARErrorType var1, String var2) {}
> ...
> @Override
> public void frameAvailable(Image var1) {}
> ...
> }
> ```

can you explain in more detail

**Comment by shivo-ham** [comment]
its notworking
